### ISSUE TITLE
Mod errors 

### ISSUE THREAD

**Issue by Alucard0Reborn** [A1y0sh4/The-Great-Civ-Rework#2]
Religious Art's unique "[+3 Faith] <in cities with at least [1] [Artist]>" contains the conditional "in cities with at least [1] [Artist]". This contains the parameter Artist which does not fit parameter type populationFilter !
God of War's unique "Earn [50]% of killed [Military] unit's [Strength] as [Faith]" cannot be put on this type of object!
your exploring unit receives training's unique "This Unit gains [10]-[20] XP" looks like it may be a misspelling of:
	"This Unit gains [amount] XP"
survivors (adds population to a city)'s unique "[+1]-[+2] population in a random city" looks like it may be a misspelling of:
	"[amount] population in a random city"

**Comment by A1y0sh4** [comment]
Thank you for the time that you dedicated for informing me of the issues, now they should all be resolved.
Have a lovely day ^^
